export const ingredientsInfo: { [key: string]: { [key: string]: string } } = {
  'Коробки под пиццу': { imagePath: 'pizza-box.png', type: 'Прочее' },
  'Салфетки': { imagePath: 'wipes.png', type: 'Прочее' },
  'Тесто': { imagePath: 'dough.png', type: 'Тесто' },
  'Мука': { imagePath: 'flour.png', type: 'Тесто' },
  'Соус томатный': { imagePath: 'tomato-sauce.png', type: 'Соусы' },
  'Соус сливочный': { imagePath: 'cream-sauce.png', type: 'Соусы' },
  'Сыр Моцарелла': { imagePath: 'mozzarella-cheese.png', type: 'Сыры' },
  'Сыр Пармезан': { imagePath: 'parmesan-cheese.png', type: 'Сыры' },
  'Сыр Дор Блю': { imagePath: 'dor-blue-cheese.png', type: 'Сыры' },
  'Бекон': { imagePath: 'bacon.png', type: 'Мясо' },
  'Ветчина': { imagePath: 'ham.png', type: 'Мясо' },
  'Сервелат': { imagePath: 'sarvelat.png', type: 'Мясо' },
  'Пепперони': { imagePath: 'pepperoni.png', type: 'Мясо' },
  'Курица маринованная': { imagePath: 'marinated-chicken.png', type: 'Мясо' },
  'Шампиньоны': { imagePath: 'champignons.png', type: 'Грибы' },
  'Итальянские травы': { imagePath: 'italian-herbs.png', type: 'Приправы' },
  'Томаты': { imagePath: 'tomato.png', type: 'Овощи / фрукты' },
  'Лук зеленый': { imagePath: 'green-onions.png', type: 'Овощи / фрукты' },
  'Ананас': { imagePath: 'pineapple.png', type: 'Овощи / фрукты' },
  'Оливковое масло': { imagePath: 'olive-oil.png', type: 'Масла' },
  'Масло чесночное (бокс)': { imagePath: 'garlic-oil.png', type: 'Масла' },
  'Масло перцовое (бокс)': { imagePath: 'pepper-oil.png', type: 'Масла' },
  // тест
  'Сыр': { imagePath: 'mozzarella-cheese.png', type: 'Сыры' },
  'Огурцы': { imagePath: 'green-onions.png', type: 'Овощи / фрукты' },
  'Помидоры': { imagePath: 'tomato.png', type: 'Овощи / фрукты' },
  'Колбаса': { imagePath: 'ham.png', type: 'Мясо' },

}

export const colorByType: { [key: string]: string } = {
  'Прочее': '#F2F2F2',
  'Тесто': '#F3FFAC',
  'Соусы': '#AECAFF',
  'Сыры': '#FCFF75',
  'Мясо': '#FF9494',
  'Грибы': '#FF9052',
  'Приправы': '#99FFC2',
  'Овощи / фрукты': '#A4FF8D',
  'Масла': '#FFC27B',
}
